image: mcr.microsoft.com/dotnet/sdk:5.0-focal

stages:
    - build
    - test
    - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
      - .nuget

build:
  stage: build
  script:
    - dotnet restore --packages .nuget
    - dotnet publish --configuration Release --runtime linux-x64 --output stemme src/Web
  artifacts: 
    paths:
      - stemme

test:
    stage: test
    script: 
        - dotnet restore --packages .nuget
        - dotnet test --no-restore

production:
  stage: deploy
  image: alpine
  inherit:
    default: false
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --no-cache zip curl 
    - cd stemme
    - zip -r stemme.zip .
    - curl -X POST -u "\$Stemmesystem:$AZURE_PASSWORD" --data-binary @"stemme.zip" https://stemmesystem.scm.azurewebsites.net/api/zipdeploy
  only:
    - master     
