image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test"
production:
    stage: deploy
    image: docker:latest
    script: 
    - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
    - npm i -g heroku
    - docker build . -t web
    - heroku container:push web -a stemmesystem
    - heroku container:release web -a stemmesystem
    only: 
    - master 
