image: mcr.microsoft.com/dotnet/sdk:5.0-focal

stages:
    - test
    - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
      - .nuget

test:
    stage: test
    script: 
        - dotnet restore --packages .nuget
        - dotnet test --no-restore
production:
    stage: deploy
    image: docker:latest
    services:
      - docker:dind
    variables:
      DOCKER_DRIVER: overlay
    script: 
    - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
    - npm i -g heroku
    - heroku container:login
    - docker build . -t web
    - heroku container:push web -a stemmesystem
    - heroku container:release web -a stemmesystem
    only: 
    - master 
