// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StemmeSystem.Data;
using Stemmesystem.Server.Data;

#nullable disable

namespace PostgresMigrations
{
    [DbContext(typeof(StemmesystemContext))]
    [Migration("20220124210640_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stemme")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DelegatVotering", b =>
                {
                    b.Property<int>("AvgitStemmeId")
                        .HasColumnType("integer");

                    b.Property<int>("HarStemmtIId")
                        .HasColumnType("integer");

                    b.HasKey("AvgitStemmeId", "HarStemmtIId");

                    b.HasIndex("HarStemmtIId");

                    b.ToTable("DelegatVotering", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Arrangement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Sluttdato")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Startdato")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Arrangement", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Delegat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrangementId")
                        .HasColumnType("integer");

                    b.Property<string>("Delegatkode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Delegatnummer")
                        .HasColumnType("integer");

                    b.Property<string>("Epost")
                        .HasColumnType("text");

                    b.Property<string>("Gruppe")
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SendtEmail")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SendtSms")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Delegatkode")
                        .IsUnique();

                    b.HasIndex("ArrangementId", "Delegatnummer")
                        .IsUnique();

                    b.ToTable("Delegat", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Sak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrangementId")
                        .HasColumnType("integer");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArrangementId");

                    b.ToTable("Sak", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Stemme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DelegatId")
                        .HasColumnType("integer");

                    b.Property<string>("StemmeHash")
                        .HasColumnType("text");

                    b.Property<Guid>("ValgId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VoteringId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DelegatId");

                    b.HasIndex("VoteringId");

                    b.ToTable("Stemme", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Votering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<bool>("Hemmelig")
                        .HasColumnType("boolean");

                    b.Property<int>("KanVelge")
                        .HasColumnType("integer");

                    b.Property<bool>("Lukket")
                        .HasColumnType("boolean");

                    b.Property<bool>("Publisert")
                        .HasColumnType("boolean");

                    b.Property<int>("SakId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SluttTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SakId");

                    b.ToTable("Votering", "stemme");
                });

            modelBuilder.Entity("DelegatVotering", b =>
                {
                    b.HasOne("Stemmesystem.Server.Data.Entities.Delegat", null)
                        .WithMany()
                        .HasForeignKey("AvgitStemmeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Stemmesystem.Server.Data.Entities.Votering", null)
                        .WithMany()
                        .HasForeignKey("HarStemmtIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Delegat", b =>
                {
                    b.HasOne("Stemmesystem.Server.Data.Entities.Arrangement", "Arrangement")
                        .WithMany("Delegater")
                        .HasForeignKey("ArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrangement");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Sak", b =>
                {
                    b.HasOne("Stemmesystem.Server.Data.Entities.Arrangement", "Arrangement")
                        .WithMany("Saker")
                        .HasForeignKey("ArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrangement");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Stemme", b =>
                {
                    b.HasOne("Stemmesystem.Server.Data.Entities.Delegat", "Delegat")
                        .WithMany()
                        .HasForeignKey("DelegatId");

                    b.HasOne("Stemmesystem.Server.Data.Entities.Votering", null)
                        .WithMany("Stemmer")
                        .HasForeignKey("VoteringId");

                    b.Navigation("Delegat");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Votering", b =>
                {
                    b.HasOne("Stemmesystem.Server.Data.Entities.Sak", "Sak")
                        .WithMany("Voteringer")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Stemmesystem.Server.Data.Entities.Valg", "Valg", b1 =>
                        {
                            b1.Property<int>("VoteringId")
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Navn")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("SortId")
                                .HasColumnType("integer");

                            b1.HasKey("VoteringId", "Id");

                            b1.ToTable("Valg", "stemme");

                            b1.WithOwner()
                                .HasForeignKey("VoteringId");
                        });

                    b.Navigation("Sak");

                    b.Navigation("Valg");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Arrangement", b =>
                {
                    b.Navigation("Delegater");

                    b.Navigation("Saker");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Sak", b =>
                {
                    b.Navigation("Voteringer");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Votering", b =>
                {
                    b.Navigation("Stemmer");
                });
#pragma warning restore 612, 618
        }
    }
}
