// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stemmesystem.Data;

#nullable disable

namespace StemmeSystem.Data.Migrations
{
    [DbContext(typeof(StemmesystemContext))]
    [Migration("20250121185443_removed identityserver")]
    partial class RemovedIdentityServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stemme")
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DelegatVotering", b =>
                {
                    b.Property<int>("AvgitStemmeId")
                        .HasColumnType("integer");

                    b.Property<int>("HarStemmtIId")
                        .HasColumnType("integer");

                    b.HasKey("AvgitStemmeId", "HarStemmtIId");

                    b.HasIndex("HarStemmtIId");

                    b.ToTable("DelegatVotering", "stemme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "stemme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "stemme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "stemme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "stemme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "stemme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "stemme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Delegat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrangementId")
                        .HasColumnType("integer");

                    b.Property<string>("Delegatkode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Delegatnummer")
                        .HasColumnType("integer");

                    b.Property<string>("Epost")
                        .HasColumnType("text");

                    b.Property<string>("Gruppe")
                        .HasColumnType("text");

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Navn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SendtEmailInternal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SendtEmail");

                    b.Property<DateTimeOffset?>("SendtSmsInternal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SendtSms");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<bool>("TilStede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Delegatkode")
                        .IsUnique();

                    b.HasIndex("ArrangementId", "Delegatnummer")
                        .IsUnique();

                    b.ToTable("Delegat", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Sak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrangementId")
                        .HasColumnType("integer");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArrangementId");

                    b.ToTable("Sak", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Stemme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DelegatId")
                        .HasColumnType("integer");

                    b.Property<string>("StemmeHash")
                        .HasColumnType("text");

                    b.Property<Guid>("ValgId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VoteringId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DelegatId");

                    b.HasIndex("VoteringId");

                    b.ToTable("Stemme", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Votering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<int?>("DelegaterTilstede")
                        .HasColumnType("integer");

                    b.Property<bool>("Hemmelig")
                        .HasColumnType("boolean");

                    b.Property<int>("KanVelge")
                        .HasColumnType("integer");

                    b.Property<bool>("Lukket")
                        .HasColumnType("boolean");

                    b.Property<bool>("Publisert")
                        .HasColumnType("boolean");

                    b.Property<int>("SakId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SluttTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SakId");

                    b.ToTable("Votering", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "stemme");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Arrangement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Sluttdato")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Startdato")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Arrangement", "stemme");
                });

            modelBuilder.Entity("DelegatVotering", b =>
                {
                    b.HasOne("Stemmesystem.Data.Entities.Delegat", null)
                        .WithMany()
                        .HasForeignKey("AvgitStemmeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Stemmesystem.Data.Entities.Votering", null)
                        .WithMany()
                        .HasForeignKey("HarStemmtIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Stemmesystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Stemmesystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stemmesystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Stemmesystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Delegat", b =>
                {
                    b.HasOne("Stemmesystem.Server.Data.Entities.Arrangement", "Arrangement")
                        .WithMany("Delegater")
                        .HasForeignKey("ArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrangement");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Sak", b =>
                {
                    b.HasOne("Stemmesystem.Server.Data.Entities.Arrangement", "Arrangement")
                        .WithMany("Saker")
                        .HasForeignKey("ArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrangement");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Stemme", b =>
                {
                    b.HasOne("Stemmesystem.Data.Entities.Delegat", "Delegat")
                        .WithMany()
                        .HasForeignKey("DelegatId");

                    b.HasOne("Stemmesystem.Data.Entities.Votering", null)
                        .WithMany("Stemmer")
                        .HasForeignKey("VoteringId");

                    b.Navigation("Delegat");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Votering", b =>
                {
                    b.HasOne("Stemmesystem.Data.Entities.Sak", "Sak")
                        .WithMany("Voteringer")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Stemmesystem.Server.Data.Entities.Valg", "Valg", b1 =>
                        {
                            b1.Property<int>("VoteringId")
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Navn")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("SortId")
                                .HasColumnType("integer");

                            b1.HasKey("VoteringId", "Id");

                            b1.ToTable("Valg", "stemme");

                            b1.WithOwner()
                                .HasForeignKey("VoteringId");
                        });

                    b.Navigation("Sak");

                    b.Navigation("Valg");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Arrangement", b =>
                {
                    b.OwnsOne("Stemmesystem.Server.Data.Entities.MinSpeidingOptions", "MinSpeidingOptions", b1 =>
                        {
                            b1.Property<int>("ArrangementId")
                                .HasColumnType("integer");

                            b1.Property<string>("Filter")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<bool>("ImportCheckIn")
                                .HasColumnType("boolean");

                            b1.Property<string>("MembersApiKey")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("MinSpeidingId")
                                .HasColumnType("integer");

                            b1.HasKey("ArrangementId");

                            b1.ToTable("Arrangement", "stemme");

                            b1.WithOwner()
                                .HasForeignKey("ArrangementId");
                        });

                    b.Navigation("MinSpeidingOptions");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Sak", b =>
                {
                    b.Navigation("Voteringer");
                });

            modelBuilder.Entity("Stemmesystem.Data.Entities.Votering", b =>
                {
                    b.Navigation("Stemmer");
                });

            modelBuilder.Entity("Stemmesystem.Server.Data.Entities.Arrangement", b =>
                {
                    b.Navigation("Delegater");

                    b.Navigation("Saker");
                });
#pragma warning restore 612, 618
        }
    }
}
