// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stemmesystem.Data;

namespace PostgresMigrations
{
    [DbContext(typeof(StemmesystemContext))]
    [Migration("20210112231240_ChangedCasing")]
    partial class ChangedCasing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stemme")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DelegatVotering", b =>
                {
                    b.Property<int>("AvgitStemmeId")
                        .HasColumnType("integer");

                    b.Property<int>("HarStemmtIId")
                        .HasColumnType("integer");

                    b.HasKey("AvgitStemmeId", "HarStemmtIId");

                    b.HasIndex("HarStemmtIId");

                    b.ToTable("DelegatVotering");
                });

            modelBuilder.Entity("Stemmesystem.Data.Arrangement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Arrangement");
                });

            modelBuilder.Entity("Stemmesystem.Data.Delegat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ArrangementId")
                        .HasColumnType("integer");

                    b.Property<string>("Delegatkode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Delegatnummer")
                        .HasColumnType("integer");

                    b.Property<string>("Epost")
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Delegatkode")
                        .IsUnique();

                    b.HasIndex("ArrangementId", "Delegatnummer")
                        .IsUnique();

                    b.ToTable("Delegat");
                });

            modelBuilder.Entity("Stemmesystem.Data.Sak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ArrangementId")
                        .HasColumnType("integer");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<int>("Nummer")
                        .HasColumnType("integer");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArrangementId");

                    b.ToTable("Sak");
                });

            modelBuilder.Entity("Stemmesystem.Data.Stemme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DelegatId")
                        .HasColumnType("integer");

                    b.Property<string>("RevoteKey")
                        .HasColumnType("text");

                    b.Property<Guid>("ValgId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VoteringId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DelegatId");

                    b.HasIndex("VoteringId");

                    b.ToTable("Stemme");
                });

            modelBuilder.Entity("Stemmesystem.Data.Votering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<bool>("Hemmelig")
                        .HasColumnType("boolean");

                    b.Property<int>("SakId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SluttTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SakId");

                    b.ToTable("Votering");
                });

            modelBuilder.Entity("DelegatVotering", b =>
                {
                    b.HasOne("Stemmesystem.Data.Delegat", null)
                        .WithMany()
                        .HasForeignKey("AvgitStemmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stemmesystem.Data.Votering", null)
                        .WithMany()
                        .HasForeignKey("HarStemmtIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stemmesystem.Data.Delegat", b =>
                {
                    b.HasOne("Stemmesystem.Data.Arrangement", "Arrangement")
                        .WithMany("Delegater")
                        .HasForeignKey("ArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrangement");
                });

            modelBuilder.Entity("Stemmesystem.Data.Sak", b =>
                {
                    b.HasOne("Stemmesystem.Data.Arrangement", "Arrangement")
                        .WithMany("Saker")
                        .HasForeignKey("ArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrangement");
                });

            modelBuilder.Entity("Stemmesystem.Data.Stemme", b =>
                {
                    b.HasOne("Stemmesystem.Data.Delegat", "Delegat")
                        .WithMany()
                        .HasForeignKey("DelegatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stemmesystem.Data.Votering", null)
                        .WithMany("Stemmer")
                        .HasForeignKey("VoteringId");

                    b.Navigation("Delegat");
                });

            modelBuilder.Entity("Stemmesystem.Data.Votering", b =>
                {
                    b.HasOne("Stemmesystem.Data.Sak", "Sak")
                        .WithMany("Voteringer")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Stemmesystem.Data.Valg", "Valg", b1 =>
                        {
                            b1.Property<int>("VoteringId")
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Navn")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("SortId")
                                .HasColumnType("integer");

                            b1.HasKey("VoteringId", "Id");

                            b1.ToTable("Valg");

                            b1.WithOwner()
                                .HasForeignKey("VoteringId");
                        });

                    b.Navigation("Sak");

                    b.Navigation("Valg");
                });

            modelBuilder.Entity("Stemmesystem.Data.Arrangement", b =>
                {
                    b.Navigation("Delegater");

                    b.Navigation("Saker");
                });

            modelBuilder.Entity("Stemmesystem.Data.Sak", b =>
                {
                    b.Navigation("Voteringer");
                });

            modelBuilder.Entity("Stemmesystem.Data.Votering", b =>
                {
                    b.Navigation("Stemmer");
                });
#pragma warning restore 612, 618
        }
    }
}
